### ISSUE TITLE
Use organization account for @privacybychoice?

### ISSUE THREAD

**Issue by chibicode** [privacybychoice/privacybychoice.github.io#2]
It seems that @privacybychoice is currently a personal account, but it might make sense to have it as an organization account so that (1) it's not associated under someone's name (currently it says Bill Fitzgerald) and (2) it's more open for others to join.

https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by billfitzgerald** [comment]
Agreed. This is definitely on the roadmap, and will definitely happen.

**Comment by chibicode** [comment]
:+1: thanks!

**Comment by billfitzgerald** [comment]
And this "Bill Fitzgerald" character - he's shifty :)

**Comment by farazfazli** [comment]
Hi @billfitzgerald, any update on this?

**Comment by billfitzgerald** [comment]
This has been low on the priority list - hasn't happened yet.

I'm wide open to other committers on this, if anyone is interested.

**Comment by farazfazli** [comment]
Hey Bill! It's just a single button in settings to turn your account into an organization: https://github.com/settings/organizations

**Comment by billfitzgerald** [comment]
Like I said, it was a low priority :)

Okay - done!

**Comment by farazfazli** [comment]
@billfitzgerald Sure, no problem. I really like the concept of this!
